### ISSUE TITLE
Check which apps should exist

### ISSUE THREAD

**Issue by ptrstn** [ptrstn/certifier#1]
Determine which apps should be used for the new certification helper and rename the relevant files accordingly.

Examples:

Project name: tkdqmdoctor

Apps:
- certifier: Contains models and tracker data certification related things
- analyser: To be used for machine learning algorithms
- oms: everything related for retrieving data from the oms
- runreg: everything related for retrieving data from the Run Registry
- dqmgui: everything related for retrieving data from the DQM GUI

**Comment by alingrig** [comment]
Apps:

- certifier: Contains models and tracker data certification related things
- analyser: To be used for machine learning algorithms
- oms: everything related for retrieving data from the oms
- runreg: everything related for retrieving data from the Run Registry
- dqmgui: everything related for retrieving data from the DQM GUI
- reports: shift leader report and daily report
- charts: all charts used across the site

**Comment by ptrstn** [comment]
Closed in dc2708b05028b9e2514c42d9287cda3837869a31
